---

- name: Get docker apt repo gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Create apt repo
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    update_cache: yes

- name: Install Docker Engine
  ansible.builtin.apt:
     name: "{{ docker_packages }}"

- name: Copy Docker's daemon.json file
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/
    owner: root
    group: root
    mode: 0644
  notify: restart docker

- name: Add non-root users to docker group
  ansible.builtin.user:
    name: "{{ item.user }}"
    groups: docker
    append: yes
  with_items: "{{ rpi_users }}"
