apiVersion: kubeadm.k8s.io/v1beta2
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.20.51:6443
    token: nsjuhv.dmy91zmnkb4n027z
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: nsjuhv.dmy91zmnkb4n027z
kind: JoinConfiguration
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  taints: null
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
