---

- name: reboot server
  reboot:

- name: restart docker
  ansible.builtin.systemd:
    state: restarted
    name: docker.service

- name: restart containerd
  ansible.builtin.systemd:
    state: restarted
    name: containerd.service
