---
assorted_apts:
  - libraspberrypi-bin
  - rpi-eeprom
  - tftp-hpa
  - nfs-common
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg2
  - lsscsi
  - sg3-utils
  - multipath-tools
  - scsitools