#
# All users that need common files (.vimrc, profiles, etc)
#
rpi_users:
  - user: wook
    home: /home/wook/
  - user: kube
    home: /home/kube

rpi_all_users:
  - user: root
    home: /root/
  - user: wook
    home: /home/wook/
  - user: kube
    home: /home/kube
